### ISSUE TITLE
Server `.status.powerState` is not polled frequently

### ISSUE THREAD

**Issue by defo89** [ironcore-dev/metal-operator#121]
**To Reproduce**
Create `ServerClaim` that binds to the server, wait for server to deploy, remove ServerClaim and observe that Servers `powerState` is not updated for a longer time

**Comment by afritzler** [comment]
Maybe we should do a `wait.Until` before we patch the `PowerState` of the `Server`.

**Comment by stefanhipfel** [comment]
that is odd, since in the server reconcile we check `server.Spec.ServerClaimRef == nil` and patch the state to `Available`. In the next loop the `updateServerStatus` is called which should check for the powerState.

In the `handleAvailableState` function we turn off the server. This function however never returns true to be re-queued.
